### ISSUE TITLE
callvirt instance support

### ISSUE THREAD

**Issue by SomeUserName6474** [oleg-st/InlineMethod.Fody#1]
Calling method from object.
When i call method from struct with interface, like a.GetValue(), i get 

 ```IL_002c: callvirt instance !0 class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32>::GetValue()```

Even if interface and target method has InlineMethod attribute.

Can you add InlineMethod.Fody support for this case?

**Comment by oleg-st** [comment]
I think `callvirt`'s target method can be determined at runtime only
Do you have a sample of code for this case?

**Comment by SomeUserName6474** [comment]
Not needed. Now making weaver for custom INumeric without any reference to interface for ilgpu.
