### ISSUE TITLE
Inlining and Stackalloc?

### ISSUE THREAD

**Issue by adamhathcock** [oleg-st/InlineMethod.Fody#2]
Hi,

I'm attempting to integrate your Zstandard lib into Sharpcompress for Zstandard file support.  What I'm coming across is that this Inlining seems to be affecting a lot of stackalloc usage and I have to remove it to make things behave correctly.

This can be seen behaviorly by looking at this commit and I had to remove two stackalloc arrays to make tests specific to this code area pass: https://github.com/adamhathcock/sharpcompress/pull/627/commits/aedda0a95ec52ddd2ab57962df86adeaa5063e1e

I could be wrong but I think it's this specific weaver.  Do you have any idea why this would be the case?

Thanks for this and the zstd lib!

**Comment by oleg-st** [comment]
Hello,

`stackalloc` is maybe affected by `[module: SkipLocalsInit]` attribute in `UnsafeHelper.cs`. It's module wide here so it can affect the whole project.

**Comment by adamhathcock** [comment]
That was it, thanks!

Never came across that attribute before.
