### ISSUE TITLE
Issue a warning if a method is not inlined

### ISSUE THREAD

**Issue by WalkerCodeRanger** [oleg-st/InlineMethod.Fody#5]
I see a few methods get inlined, but I see other places where they are not. I don't know why that is. You should issue a warning when inlining fails.

**Comment by oleg-st** [comment]
Could you provide the repro project?

**Comment by oleg-st** [comment]
I think when inlining fails an exception should be thrown

**Comment by WalkerCodeRanger** [comment]
Closing because I can't reproduce this anymore
