### ISSUE TITLE
Automatically set `<PrivateAssets>all</PrivateAssets>`

### ISSUE THREAD

**Issue by WalkerCodeRanger** [oleg-st/InlineMethod.Fody#9]
There is some way to configure the NuGet package to automatically add `<PrivateAssets>all</PrivateAssets>` when the package is added in Visual Studio. Even `Fody` itself does this for v6.8.1. It would be good to set that up and then you wouldn't have that setup step and the install and setup would be eaiser.

**Comment by oleg-st** [comment]
Fody has `<DevelopmentDependency>true</DevelopmentDependency>`, which adds
`<PrivateAssets>all</PrivateAssets>` and `<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>` to `<PackageReference>`.

We only need `PrivateAssets="all"` without `<IncludeAssets>`.
I don't see any Fody addins that automatically set `<PrivateAssets>`.
